language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install bundler
  - gem install github-pages
  - gem install jekyll
  - gem install jekyll-paginate
script:
  - bundle install
  - bundle exec jekyll build
after_success:
  - bash <(curl -s https://codecov.io/bash)


